### ISSUE TITLE
Upgrading theia-cloud from 0.8.0.MS7 to 0.12.0 failed

### ISSUE THREAD

**Issue by NickLagogiannis** [eclipse-theia/theia-cloud#376]
### Describe the bug

Greetings,

Previously, we had successfully installed theia cloud on Azure by following these instructions: [https://github.com/eclipse-theia/theia-cloud/blob/azure-documentation/doc/docs/platforms/Azure.md](url)

However, because of the valuesAzure.yaml  file of this project used images in version 0.8.0.MS7 , we tried to update them in the latest version 0.12.0 . 

When we tried to reinstall it with Helm, we had issues with the operator pod. Specifically,  cloudProvider value  in valuesAzure.yaml was "GKE" , we change it in "K8S" (line 41 of screenshot valuesAzure below) and also instancesHost argument was missing (as stated in screenshot logfile excerpt below), we added it in the deployment file of operator pod (c.f. screenshot operator pod deployment file) and the pod was restarted successfully.

Nevertheless, when we tried to access the app from the browser the following error occurred: "ERROR: The app definition 'theia-cloud-demo' is not available in the cluster.
Please try launching another application."

<img src="https://github.com/user-attachments/assets/a229d8c8-775e-4e72-ae3b-23aa8f4eba11" alt="browserPage" width="60%">

This is our app definition:
![appDefinition](https://github.com/user-attachments/assets/cb350243-75ae-46f6-9a5c-0f088836b0b9)

This is our valuesAzure file:
![valuesAzure1](https://github.com/user-attachments/assets/6ab049fd-9cb2-42cb-91a2-3f3f0a7ee804)
![valuesAzure2](https://github.com/user-attachments/assets/acb2a56e-7780-4e62-9ce3-656b0175fdec)

This is our logfile excerpt:
![operator-logfile](https://github.com/user-attachments/assets/c4c63324-69fb-4c7d-b6d5-a0c49f920a94)

This is our operator pod  deployment file:
![operator-deployment](https://github.com/user-attachments/assets/85945227-2011-4fd8-a07c-b71ccc22a6e6)

We don't know how to proceed. Is the valuesAzure.yaml outdated or is there another issue? Also if its outdated where can we find a new one?

### Expected behavior

I expected to launch the application

**Comment by jfaltermeier** [comment]
Hi, we did not have the resources to maintain or test the dedicated Azure values, so this PR was never merged, and the values file was not updated.

From a Theia Cloud perspective, I don’t think there was anything specific to Azure in these values. At the time, we used "GKE" as the cloud provider, which has since been renamed to "K8S" as the general default cloud provider. Other than that, the guide primarily focused on setting up a cluster on Azure and installing non-Theia Cloud components.

Here are some resources that might help:

- Changelogs with details on how Helm values have changed
  - https://github.com/eclipse-theia/theia-cloud-helm/blob/main/CHANGELOG.md
  - https://github.com/eclipse-theia/theia-cloud/blob/main/CHANGELOG.md
- README with more information about each value https://github.com/eclipse-theia/theia-cloud-helm/blob/theia-cloud-0.12.0/README.md
- Example values file used for testing the try-now demo: https://github.com/eclipse-theia/theia-cloud/blob/0.12.0/terraform/values/valuesDemo.yaml

I hope this helps
